[package]
name = "credit-engine-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
num-bigint = "0.4"
num-integer = "0.1"
num-rational = "0.4"
num-traits = "0.2"
opentelemetry = { version = "0.29", features = ["trace", "metrics"] }
opentelemetry-otlp = { version = "0.29", features = ["http-proto"] }
opentelemetry_sdk = { version = "0.29", features = ["metrics", "rt-tokio"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tracing = "0.1"
tracing-opentelemetry = "0.30"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
uint = "0.9"

[dev-dependencies]
proptest = "1"
criterion = { version = "0.5", default-features = false }

# (removed) golden_runner bin block
num-bigint = "0.4"
num-integer = "0.1"
num-rational = "0.4"
num-traits = "0.2"


["rlib"]


[lib]
name = "credit_engine_core"
path = "src/lib.rs"
crate-type = ["rlib"]
num-bigint = "0.4"
num-integer = "0.1"
num-rational = "0.4"
num-traits = "0.2"

[[bench]]
name = "bench_swap"
harness = false

[[bench]]
name = "bench_liquidity"
harness = false
