[package]
name = "credit-engine-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "ce_core"
path = "src/lib.rs"

[dependencies]
uint = "0.9"
num-traits = "0.2"

[dev-dependencies]
proptest = "1"
criterion = { version = "0.5", default-features = false }
