services:
  otlp-bridge:
    image: nginx:1.25-alpine
    volumes:
      - ./ops/nginx/otlp-bridge.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "4319:4319"
    depends_on:
      - otel-collector
    restart: unless-stopped

  otlp-metrics-bridge:
    image: nginx:1.25-alpine
    volumes:
      - ./ops/nginx/otlp-metrics.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "4320:4320"
    depends_on:
      - otel-collector
    restart: unless-stopped
