global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otelcol-self'
    static_configs:
      - targets: ['otel-collector:8888']

  # Only valid when using the Prometheus exporter variant
  - job_name: 'otelcol-pipeline'
    static_configs:
      - targets: ['otel-collector:9464']
