name: Semantic PR Title

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

jobs:
  lint-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    steps:
      - name: Validate title
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            chore
            docs
            refactor
            test
            build
            ci
          requireScope: false
          subjectPattern: ^[a-zA-Z0-9].+
